apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #deployment name, helps uniquely identify the object
   name: react
spec:  
  selector:
    matchLabels:
      app: react
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: react
    spec:   #What state you desire for the object
      containers:
      - name: react #container name
        image: 'shoaib8055/react-dep:react' #image name
        ports:
        - containerPort: 3000 # demo runs on port 8080
---
apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name,Data that helps uniquely identify the object
  name: react
spec: #What state you desire for the object
  selector:
    app: react
  ports:
    - port: 80  #port at which service is internally available
      targetPort: 3000 #port of container
      #nodePort: 30001  # port at which service is externally available  range 30000- 32767 
      name: react
  type: LoadBalancer